/**
 * DataForSEO Labs / AI Optimization endpoints (related_keywords, keyword_ideas, keyword_overview,
 * ranked_keywords, search_intent, subdomains, top_searches, domain/page intersection, competitors,
 * historical_rank_overview, categories_for_domain, bulk_keyword_difficulty, bulk_traffic_estimation,
 * ai_keyword_data, llm_mentions) only support location targeting at the country level — confirmed via
 * their `locations_and_languages` reference endpoints, which return this exact 94-entry list regardless
 * of country. Passing a city/region location_name to these endpoints fails, unlike SERP-based endpoints
 * (organic search, local finder, business data) which support full city/region granularity.
 */
export const LABS_LOCATIONS = [
  { code: 2008, name: 'Albania', iso: 'AL' },
  { code: 2012, name: 'Algeria', iso: 'DZ' },
  { code: 2024, name: 'Angola', iso: 'AO' },
  { code: 2032, name: 'Argentina', iso: 'AR' },
  { code: 2051, name: 'Armenia', iso: 'AM' },
  { code: 2036, name: 'Australia', iso: 'AU' },
  { code: 2040, name: 'Austria', iso: 'AT' },
  { code: 2031, name: 'Azerbaijan', iso: 'AZ' },
  { code: 2048, name: 'Bahrain', iso: 'BH' },
  { code: 2050, name: 'Bangladesh', iso: 'BD' },
  { code: 2056, name: 'Belgium', iso: 'BE' },
  { code: 2068, name: 'Bolivia', iso: 'BO' },
  { code: 2070, name: 'Bosnia and Herzegovina', iso: 'BA' },
  { code: 2076, name: 'Brazil', iso: 'BR' },
  { code: 2100, name: 'Bulgaria', iso: 'BG' },
  { code: 2854, name: 'Burkina Faso', iso: 'BF' },
  { code: 2116, name: 'Cambodia', iso: 'KH' },
  { code: 2120, name: 'Cameroon', iso: 'CM' },
  { code: 2124, name: 'Canada', iso: 'CA' },
  { code: 2152, name: 'Chile', iso: 'CL' },
  { code: 2170, name: 'Colombia', iso: 'CO' },
  { code: 2188, name: 'Costa Rica', iso: 'CR' },
  { code: 2384, name: "Cote d'Ivoire", iso: 'CI' },
  { code: 2191, name: 'Croatia', iso: 'HR' },
  { code: 2196, name: 'Cyprus', iso: 'CY' },
  { code: 2203, name: 'Czechia', iso: 'CZ' },
  { code: 2208, name: 'Denmark', iso: 'DK' },
  { code: 2218, name: 'Ecuador', iso: 'EC' },
  { code: 2818, name: 'Egypt', iso: 'EG' },
  { code: 2222, name: 'El Salvador', iso: 'SV' },
  { code: 2233, name: 'Estonia', iso: 'EE' },
  { code: 2246, name: 'Finland', iso: 'FI' },
  { code: 2250, name: 'France', iso: 'FR' },
  { code: 2276, name: 'Germany', iso: 'DE' },
  { code: 2288, name: 'Ghana', iso: 'GH' },
  { code: 2300, name: 'Greece', iso: 'GR' },
  { code: 2320, name: 'Guatemala', iso: 'GT' },
  { code: 2344, name: 'Hong Kong', iso: 'HK' },
  { code: 2348, name: 'Hungary', iso: 'HU' },
  { code: 2356, name: 'India', iso: 'IN' },
  { code: 2360, name: 'Indonesia', iso: 'ID' },
  { code: 2372, name: 'Ireland', iso: 'IE' },
  { code: 2376, name: 'Israel', iso: 'IL' },
  { code: 2380, name: 'Italy', iso: 'IT' },
  { code: 2392, name: 'Japan', iso: 'JP' },
  { code: 2400, name: 'Jordan', iso: 'JO' },
  { code: 2398, name: 'Kazakhstan', iso: 'KZ' },
  { code: 2404, name: 'Kenya', iso: 'KE' },
  { code: 2428, name: 'Latvia', iso: 'LV' },
  { code: 2440, name: 'Lithuania', iso: 'LT' },
  { code: 2458, name: 'Malaysia', iso: 'MY' },
  { code: 2470, name: 'Malta', iso: 'MT' },
  { code: 2484, name: 'Mexico', iso: 'MX' },
  { code: 2498, name: 'Moldova', iso: 'MD' },
  { code: 2492, name: 'Monaco', iso: 'MC' },
  { code: 2504, name: 'Morocco', iso: 'MA' },
  { code: 2104, name: 'Myanmar (Burma)', iso: 'MM' },
  { code: 2528, name: 'Netherlands', iso: 'NL' },
  { code: 2554, name: 'New Zealand', iso: 'NZ' },
  { code: 2558, name: 'Nicaragua', iso: 'NI' },
  { code: 2566, name: 'Nigeria', iso: 'NG' },
  { code: 2807, name: 'North Macedonia', iso: 'MK' },
  { code: 2578, name: 'Norway', iso: 'NO' },
  { code: 2586, name: 'Pakistan', iso: 'PK' },
  { code: 2591, name: 'Panama', iso: 'PA' },
  { code: 2600, name: 'Paraguay', iso: 'PY' },
  { code: 2604, name: 'Peru', iso: 'PE' },
  { code: 2608, name: 'Philippines', iso: 'PH' },
  { code: 2616, name: 'Poland', iso: 'PL' },
  { code: 2620, name: 'Portugal', iso: 'PT' },
  { code: 2642, name: 'Romania', iso: 'RO' },
  { code: 2682, name: 'Saudi Arabia', iso: 'SA' },
  { code: 2686, name: 'Senegal', iso: 'SN' },
  { code: 2688, name: 'Serbia', iso: 'RS' },
  { code: 2702, name: 'Singapore', iso: 'SG' },
  { code: 2703, name: 'Slovakia', iso: 'SK' },
  { code: 2705, name: 'Slovenia', iso: 'SI' },
  { code: 2710, name: 'South Africa', iso: 'ZA' },
  { code: 2410, name: 'South Korea', iso: 'KR' },
  { code: 2724, name: 'Spain', iso: 'ES' },
  { code: 2144, name: 'Sri Lanka', iso: 'LK' },
  { code: 2752, name: 'Sweden', iso: 'SE' },
  { code: 2756, name: 'Switzerland', iso: 'CH' },
  { code: 2158, name: 'Taiwan', iso: 'TW' },
  { code: 2764, name: 'Thailand', iso: 'TH' },
  { code: 2788, name: 'Tunisia', iso: 'TN' },
  { code: 2792, name: 'Turkiye', iso: 'TR' },
  { code: 2804, name: 'Ukraine', iso: 'UA' },
  { code: 2784, name: 'United Arab Emirates', iso: 'AE' },
  { code: 2826, name: 'United Kingdom', iso: 'GB' },
  { code: 2840, name: 'United States', iso: 'US' },
  { code: 2858, name: 'Uruguay', iso: 'UY' },
  { code: 2862, name: 'Venezuela', iso: 'VE' },
  { code: 2704, name: 'Vietnam', iso: 'VN' },
];

/**
 * The global `default_location` setting stores a full "City,Region,Country" string (needed for
 * SERP-based tools like Local Finder). Labs/AI Optimization endpoints only accept a bare country
 * name, so pull the country segment out of that string — checked from the end, since country is
 * always last — and fall back if none of the segments match a supported Labs country.
 */
export function toLabsCountry(location: string, fallback = 'United Kingdom'): string {
  const segments = location.split(',').map((s) => s.trim()).filter(Boolean);
  for (let i = segments.length - 1; i >= 0; i--) {
    const match = LABS_LOCATIONS.find((l) => l.name.toLowerCase() === segments[i].toLowerCase());
    if (match) return match.name;
  }
  return fallback;
}

export const LOCATIONS = [
  // Europe
  { value: 'France',          label: '🇫🇷 France' },
  { value: 'Belgium',         label: '🇧🇪 Belgium' },
  { value: 'Switzerland',     label: '🇨🇭 Switzerland' },
  { value: 'Luxembourg',      label: '🇱🇺 Luxembourg' },
  { value: 'Monaco',          label: '🇲🇨 Monaco' },
  { value: 'Germany',         label: '🇩🇪 Germany' },
  { value: 'Austria',         label: '🇦🇹 Austria' },
  { value: 'Netherlands',     label: '🇳🇱 Netherlands' },
  { value: 'United Kingdom',  label: '🇬🇧 United Kingdom' },
  { value: 'Ireland',         label: '🇮🇪 Ireland' },
  { value: 'Spain',           label: '🇪🇸 Spain' },
  { value: 'Portugal',        label: '🇵🇹 Portugal' },
  { value: 'Italy',           label: '🇮🇹 Italy' },
  { value: 'Greece',          label: '🇬🇷 Greece' },
  { value: 'Poland',          label: '🇵🇱 Poland' },
  { value: 'Czech Republic',  label: '🇨🇿 Czech Republic' },
  { value: 'Slovakia',        label: '🇸🇰 Slovakia' },
  { value: 'Hungary',         label: '🇭🇺 Hungary' },
  { value: 'Romania',         label: '🇷🇴 Romania' },
  { value: 'Bulgaria',        label: '🇧🇬 Bulgaria' },
  { value: 'Croatia',         label: '🇭🇷 Croatia' },
  { value: 'Slovenia',        label: '🇸🇮 Slovenia' },
  { value: 'Serbia',          label: '🇷🇸 Serbia' },
  { value: 'Sweden',          label: '🇸🇪 Sweden' },
  { value: 'Norway',          label: '🇳🇴 Norway' },
  { value: 'Denmark',         label: '🇩🇰 Denmark' },
  { value: 'Finland',         label: '🇫🇮 Finland' },
  { value: 'Iceland',         label: '🇮🇸 Iceland' },
  { value: 'Russia',          label: '🇷🇺 Russia' },
  { value: 'Ukraine',         label: '🇺🇦 Ukraine' },
  { value: 'Turkey',          label: '🇹🇷 Turkey' },
  // Americas
  { value: 'United States',   label: '🇺🇸 United States' },
  { value: 'Canada',          label: '🇨🇦 Canada' },
  { value: 'Mexico',          label: '🇲🇽 Mexico' },
  { value: 'Brazil',          label: '🇧🇷 Brazil' },
  { value: 'Argentina',       label: '🇦🇷 Argentina' },
  { value: 'Chile',           label: '🇨🇱 Chile' },
  { value: 'Colombia',        label: '🇨🇴 Colombia' },
  { value: 'Peru',            label: '🇵🇪 Peru' },
  { value: 'Venezuela',       label: '🇻🇪 Venezuela' },
  { value: 'Uruguay',         label: '🇺🇾 Uruguay' },
  // Middle East & Africa
  { value: 'United Arab Emirates', label: '🇦🇪 United Arab Emirates' },
  { value: 'Saudi Arabia',    label: '🇸🇦 Saudi Arabia' },
  { value: 'Israel',          label: '🇮🇱 Israel' },
  { value: 'Egypt',           label: '🇪🇬 Egypt' },
  { value: 'Morocco',         label: '🇲🇦 Morocco' },
  { value: 'Algeria',         label: '🇩🇿 Algeria' },
  { value: 'Tunisia',         label: '🇹🇳 Tunisia' },
  { value: 'South Africa',    label: '🇿🇦 South Africa' },
  { value: 'Nigeria',         label: '🇳🇬 Nigeria' },
  { value: 'Kenya',           label: '🇰🇪 Kenya' },
  // Asia & Pacific
  { value: 'India',           label: '🇮🇳 India' },
  { value: 'China',           label: '🇨🇳 China' },
  { value: 'Japan',           label: '🇯🇵 Japan' },
  { value: 'South Korea',     label: '🇰🇷 South Korea' },
  { value: 'Singapore',       label: '🇸🇬 Singapore' },
  { value: 'Hong Kong',       label: '🇭🇰 Hong Kong' },
  { value: 'Taiwan',          label: '🇹🇼 Taiwan' },
  { value: 'Indonesia',       label: '🇮🇩 Indonesia' },
  { value: 'Malaysia',        label: '🇲🇾 Malaysia' },
  { value: 'Thailand',        label: '🇹🇭 Thailand' },
  { value: 'Vietnam',         label: '🇻🇳 Vietnam' },
  { value: 'Philippines',     label: '🇵🇭 Philippines' },
  { value: 'Pakistan',        label: '🇵🇰 Pakistan' },
  { value: 'Bangladesh',      label: '🇧🇩 Bangladesh' },
  { value: 'Australia',       label: '🇦🇺 Australia' },
  { value: 'New Zealand',     label: '🇳🇿 New Zealand' },
];

export const LANGUAGES = [
  { value: 'French',              label: 'Français' },
  { value: 'English',             label: 'English' },
  { value: 'German',              label: 'Deutsch' },
  { value: 'Spanish',             label: 'Español' },
  { value: 'Italian',             label: 'Italiano' },
  { value: 'Dutch',               label: 'Nederlands' },
  { value: 'Portuguese',          label: 'Português' },
  { value: 'Polish',              label: 'Polski' },
  { value: 'Russian',             label: 'Русский' },
  { value: 'Ukrainian',           label: 'Українська' },
  { value: 'Czech',               label: 'Čeština' },
  { value: 'Slovak',              label: 'Slovenčina' },
  { value: 'Hungarian',           label: 'Magyar' },
  { value: 'Romanian',            label: 'Română' },
  { value: 'Bulgarian',           label: 'Български' },
  { value: 'Croatian',            label: 'Hrvatski' },
  { value: 'Swedish',             label: 'Svenska' },
  { value: 'Norwegian',           label: 'Norsk' },
  { value: 'Danish',              label: 'Dansk' },
  { value: 'Finnish',             label: 'Suomi' },
  { value: 'Greek',               label: 'Ελληνικά' },
  { value: 'Turkish',             label: 'Türkçe' },
  { value: 'Arabic',              label: 'العربية' },
  { value: 'Hebrew',              label: 'עברית' },
  { value: 'Persian',             label: 'فارسی' },
  { value: 'Hindi',               label: 'हिन्दी' },
  { value: 'Bengali',             label: 'বাংলা' },
  { value: 'Indonesian',          label: 'Bahasa Indonesia' },
  { value: 'Malay',               label: 'Bahasa Melayu' },
  { value: 'Vietnamese',          label: 'Tiếng Việt' },
  { value: 'Thai',                label: 'ภาษาไทย' },
  { value: 'Chinese Simplified',  label: '中文 (简体)' },
  { value: 'Chinese Traditional', label: '中文 (繁體)' },
  { value: 'Japanese',            label: '日本語' },
  { value: 'Korean',              label: '한국어' },
  // Only spoken in one or two Labs/AI Optimization countries each (see LABS_LANGUAGES_BY_COUNTRY)
  // — kept out of the main block above since they'd rarely be picked outside that context.
  { value: 'Albanian',            label: 'Shqip' },
  { value: 'Armenian',            label: 'Հայերեն' },
  { value: 'Azeri',               label: 'Azərbaycan dili' },
  { value: 'Bosnian',             label: 'Bosanski' },
  { value: 'Estonian',            label: 'Eesti' },
  { value: 'Latvian',             label: 'Latviešu' },
  { value: 'Lithuanian',          label: 'Lietuvių' },
  { value: 'Macedonian',          label: 'Македонски' },
  { value: 'Serbian',             label: 'Српски' },
  { value: 'Slovenian',           label: 'Slovenščina' },
  { value: 'Tagalog',             label: 'Tagalog' },
  { value: 'Urdu',                label: 'اردو' },
];

/**
 * Labs/AI Optimization endpoints don't just restrict location to country level (see
 * `toLabsCountry`) — each country only supports a fixed, small set of languages too (usually just
 * the locally-spoken one, occasionally 2-3 for multilingual markets), confirmed against the same
 * `locations_and_languages` reference endpoints. Passing a mismatched pair (e.g. France + German)
 * returns an error or empty results depending on the endpoint.
 */
export const LABS_LANGUAGES_BY_COUNTRY: Record<string, string[]> = {
  Albania: ['Albanian'],
  Algeria: ['French', 'Arabic'],
  Angola: ['Portuguese'],
  Argentina: ['Spanish'],
  Armenia: ['Armenian'],
  Australia: ['English'],
  Austria: ['German'],
  Azerbaijan: ['Azeri'],
  Bahrain: ['Arabic'],
  Bangladesh: ['Bengali'],
  Belgium: ['French', 'Dutch', 'German'],
  Bolivia: ['Spanish'],
  'Bosnia and Herzegovina': ['Bosnian'],
  Brazil: ['Portuguese'],
  Bulgaria: ['Bulgarian'],
  'Burkina Faso': ['French'],
  Cambodia: ['English'],
  Cameroon: ['French'],
  Canada: ['English', 'French'],
  Chile: ['Spanish'],
  Colombia: ['Spanish'],
  'Costa Rica': ['Spanish'],
  'Cote d\'Ivoire': ['French'],
  Croatia: ['Croatian'],
  Cyprus: ['Greek', 'English'],
  Czechia: ['Czech'],
  Denmark: ['Danish'],
  Ecuador: ['Spanish'],
  Egypt: ['Arabic', 'English'],
  'El Salvador': ['Spanish'],
  Estonia: ['Estonian'],
  Finland: ['Finnish'],
  France: ['French'],
  Germany: ['German'],
  Ghana: ['English'],
  Greece: ['Greek', 'English'],
  Guatemala: ['Spanish'],
  'Hong Kong': ['English', 'Chinese Traditional'],
  Hungary: ['Hungarian'],
  India: ['English', 'Hindi'],
  Indonesia: ['English', 'Indonesian'],
  Ireland: ['English'],
  Israel: ['Hebrew', 'Arabic'],
  Italy: ['Italian'],
  Japan: ['Japanese'],
  Jordan: ['Arabic'],
  Kazakhstan: ['Russian'],
  Kenya: ['English'],
  Latvia: ['Latvian'],
  Lithuania: ['Lithuanian'],
  Malaysia: ['English', 'Malay'],
  Malta: ['English'],
  Mexico: ['Spanish'],
  Moldova: ['Romanian'],
  Monaco: ['French'],
  Morocco: ['Arabic', 'French'],
  'Myanmar (Burma)': ['English'],
  Netherlands: ['Dutch'],
  'New Zealand': ['English'],
  Nicaragua: ['Spanish'],
  Nigeria: ['English'],
  'North Macedonia': ['Macedonian'],
  Norway: ['Norwegian'],
  Pakistan: ['English', 'Urdu'],
  Panama: ['Spanish'],
  Paraguay: ['Spanish'],
  Peru: ['Spanish'],
  Philippines: ['English', 'Tagalog'],
  Poland: ['Polish'],
  Portugal: ['Portuguese'],
  Romania: ['Romanian'],
  'Saudi Arabia': ['Arabic'],
  Senegal: ['French'],
  Serbia: ['Serbian'],
  Singapore: ['English', 'Chinese Simplified'],
  Slovakia: ['Slovak'],
  Slovenia: ['Slovenian'],
  'South Africa': ['English'],
  'South Korea': ['Korean'],
  Spain: ['Spanish'],
  'Sri Lanka': ['English'],
  Sweden: ['Swedish'],
  Switzerland: ['German', 'French', 'Italian'],
  Taiwan: ['Chinese Traditional'],
  Thailand: ['Thai'],
  Tunisia: ['Arabic'],
  Turkiye: ['Turkish'],
  Ukraine: ['Ukrainian', 'Russian'],
  'United Arab Emirates': ['Arabic', 'English'],
  'United Kingdom': ['English'],
  'United States': ['English', 'Spanish'],
  Uruguay: ['Spanish'],
  Venezuela: ['Spanish'],
  Vietnam: ['English', 'Vietnamese'],
};

/** The LANGUAGES subset valid for a given Labs country. Falls back to the full list for an
 * unrecognized/incomplete location (e.g. mid-typing), so the field never ends up with zero options. */
export function labsLanguagesFor(country: string): typeof LANGUAGES {
  const allowed = LABS_LANGUAGES_BY_COUNTRY[country];
  if (!allowed) return LANGUAGES;
  const set = new Set(allowed);
  const filtered = LANGUAGES.filter((l) => set.has(l.value));
  return filtered.length > 0 ? filtered : LANGUAGES;
}
